services:
  # Backend API
  - type: web
    name: quantity-measurement-api
    runtime: docker
    plan: free
    region: frankfurt
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: DATABASE_URL
        fromDatabase:
          name: quantity-db
          property: connectionString
      - key: Redis
        fromService:
          type: keyvalue
          name: quantity-cache
          property: connectionString

  # Managed Redis (Key Value)
  - type: keyvalue
    name: quantity-cache
    plan: free
    region: frankfurt
    ipAllowList:
      - source: 0.0.0.0/0
        description: allow all

databases:
  # Managed PostgreSQL
  - name: quantity-db
    databaseName: quantity_measurement
    user: admin
    plan: free
    region: frankfurt
    ipAllowList:
      - source: 0.0.0.0/0
        description: allow all
