services:
  # Web API Service
  - type: web
    name: quantity-measurement-api
    env: csharp
    plan: free
    buildCommand: dotnet publish -c Release -o ./publish
    startCommand: dotnet ./publish/QuantityMeasurementWebAPI.dll
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: JWT__Key
        generateValue: true
      - key: ConnectionStrings__DefaultConnection
        value: "YOUR_DATABASE_CONNECTION_STRING_HERE"
